/*
package teste;

import static org.junit.Assert.*;
import javax.faces.context.FacesContext;





import javax.faces.validator.ValidatorException;
import javax.naming.InitialContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;


import model.Staff;

@RunWith(  PowerMockRunner.class)
// @PrepareForTest( { FacesContext.class , Staff.class } )
public class StaffTest {

	
	
    @Test
    public void test(){
    	//Staff staff = new Staff();
    //	assertEquals("Rafael", staff.getName());
    	//assertEquals(24, staff.getAge());
    }
	
    @Test
    public void testUpdateName(){
    	//Staff staff = new Staff();
    //	staff.setName("Zé");
    	//staff.setAge(25);
    //	assertEquals("Zé", staff.getName());
    	//assertEquals(25, staff.getAge());
    }
    
    @Test
    public void testValidaStaff(){
    //	Staff staff = new Staff();
    	try{
    //    staff.simplesParaTeste(null, null, "rafael@hotmail.com");
    	}catch(ValidatorException e){
    		fail("Não era esperado erro");
    	}
    }
    
    @Test
    public void testInvalidaStaff(){
    	//Staff staff = new Staff();
    	try{
    //    staff.simplesParaTeste(null, null, "rafael-hotmail.com");
        fail("Não era esperado erro");
    	}catch(RuntimeException e){
    		
    	}
    }
    
    @Test
    public void testSaveStaff(){
    	//Staff staff = new Staff();
    	//PowerMockito.mockStatic(FacesContext.class);
//    	FacesContext facesContextMock = Mockito.mock(FacesContext.class);
    	
    	//staff.saveStaff();
        
    }
    
    
    
}
*/